#!/usr/bin/env bash
set -euo pipefail
WS="/home/kavia/workspace/code-generation/uttar-pradesh-tourism-infrastructure-monitoring-system-217467-217482/upstdc_backend"
export DEBIAN_FRONTEND=noninteractive
need_install=()
# robust Java detection
JAVA_OK=0
if command -v javac >/dev/null 2>&1; then JVER=$(javac -version 2>&1 || true); else JVER=""; fi
if [ -z "${JVER:-}" ] && command -v java >/dev/null 2>&1; then JVER=$(java -XshowSettings:properties -version 2>&1 | awk -F '"' '/java.version/ {print $2; exit}' || true); fi
if [ -n "${JVER:-}" ]; then JMAJOR=$(printf '%s' "$JVER" | sed -E 's/^([0-9]+).*/\1/'); if [ "$JMAJOR" -ge 17 ]; then JAVA_OK=1; fi; fi
if [ $JAVA_OK -ne 1 ]; then need_install+=(openjdk-17-jdk); fi
# mvn detection
MVN_OK=0
MVNV=""
if command -v mvn >/dev/null 2>&1; then MVNV=$(mvn -v 2>/dev/null | awk '/Apache Maven/ {print $3; exit}' || true); fi
if [ -n "${MVNV:-}" ]; then MJR=$(printf '%s' "$MVNV" | cut -d. -f1); MMIN=$(printf '%s' "$MVNV" | cut -d. -f2 || echo 0); if [ "$MJR" -gt 3 ] || { [ "$MJR" -eq 3 ] && [ "$MMIN" -ge 8 ]; }; then MVN_OK=1; fi; fi
if [ $MVN_OK -ne 1 ]; then need_install+=(maven); fi
# jq/unzip
if ! command -v jq >/dev/null 2>&1; then need_install+=(jq); fi
if ! command -v unzip >/dev/null 2>&1; then need_install+=(unzip); fi
# install missing packages non-interactively
if [ ${#need_install[@]} -ne 0 ]; then sudo apt-get update -q && sudo apt-get install -y --no-install-recommends "${need_install[@]}" >/dev/null; fi
# re-validate existence
command -v java >/dev/null 2>&1 || { echo "ERROR: java runtime not found after attempted install" >&2; exit 2; }
command -v javac >/dev/null 2>&1 || { echo "ERROR: javac not found; ensure JDK installed" >&2; exit 3; }
if command -v mvn >/dev/null 2>&1; then MVNV=$(mvn -v 2>/dev/null | awk '/Apache Maven/ {print $3; exit}' || true); else MVNV=""; fi
# workspace and storage
mkdir -p "$WS" "$WS/storage"
# write /etc/profile.d/upstdc_env.sh atomically; avoid hardcoding runtime expansion of workspace into file (use DEFAULT with expansion preserved)
PROFILE_TMP=$(mktemp)
cat > "$PROFILE_TMP" <<'EOF'
# upstdc_env - autogenerated; safe to re-run
export SPRING_PROFILES_ACTIVE="dev"
export SERVER_PORT="8080"
# default file storage (workspace-relative) if FILE_STORAGE_PATH not set
# NOTE: FILE_STORAGE_PATH default references the authoritative workspace variable set by CI/agent; fallback to literal path below
: "${FILE_STORAGE_PATH:=${WS_STORAGE_FALLBACK:-/home/kavia/workspace/code-generation/uttar-pradesh-tourism-infrastructure-monitoring-system-217467-217482/upstdc_backend/storage}}"
export FILE_STORAGE_PATH="${FILE_STORAGE_PATH}"
# NOTE: do NOT store DB credentials here; set DB_USER/DB_PASSWORD/DATABASE_URL via container env or secret manager
EOF
# ensure sentinel idempotency
SENTINEL="# upstdc_env - autogenerated; safe to re-run"
if ! sudo grep -qF "$SENTINEL" /etc/profile.d/upstdc_env.sh 2>/dev/null; then sudo mv "$PROFILE_TMP" /etc/profile.d/upstdc_env.sh && sudo chmod 644 /etc/profile.d/upstdc_env.sh; else rm -f "$PROFILE_TMP"; fi
# final validations
java -version >/dev/null 2>&1 || { echo "ERROR: java runtime missing" >&2; exit 4; }
javac -version >/dev/null 2>&1 || { echo "ERROR: javac missing" >&2; exit 5; }
if command -v mvn >/dev/null 2>&1; then echo "maven: ${MVNV:-unknown}"; else echo "maven not available; product may generate mvnw later"; fi
exit 0
